object Versions {
    const val gradle = "4.0.0"
    const val gradlePlugin = "1.4.10"
    const val googleServicesPlugin = "4.3.10"
    const val kotlinVersionStdLib = "1.3.72"
    const val kotlinVersion = "1.7.0"
    const val fragmentKtx = "1.4.0"
    const val activityKtx = "1.4.0"
    const val viewModelKtx = "2.4.0"
    const val coroutinesVersion = "1.5.0"
    const val appCompat = "1.4.0"
    const val constrainLayout = "2.1.2"
    const val jUnit = "4.13.2"
    const val extJUnit = "1.1.3"
    const val espressoCore = "3.4.0"
    const val mockito = "4.1.0"
    const val hilt = "2.38.1"
    const val coreTesting = "2.1.0"
    const val truthVersion = "1.1.3"
    const val navigation = "2.3.5"
    const val ncapNavigation = "3.2.0"

    const val kTorVersion = "1.6.3"
}